/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ManagedUsers.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'ManagedUsers.view.MainViewModel',
        'ManagedUsers.view.MainViewController',
        'Ext.grid.Grid',
        'Ext.grid.column.Column',
        'Ext.Button'
    ],

    controller: 'main',
    viewModel: {
        type: 'main'
    },
    tabBarPosition: 'bottom',

    items: [
        {
            xtype: 'container',
            title: 'Managed Users',
            iconCls: 'x-fa fa-users',
            layout: 'vbox',
            scrollable: true,
            items: [
                
                    {
                            xtype: 'button',
                            text: 'Create Record',
                            handler:'createEmployee'
                        }
                ,
                {
                    xtype: 'grid',
                    height: '100%',
                    width: '100%',
                    store: 'Users',
                    hideHeaders: false,
                    scrollable: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'firstName',
                            text: 'First Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'lastName',
                            text: 'Last Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'email',
                            text: 'Email'
                        }
                    ],
                    listeners: {
                        childtap: 'onPopupForm'
                    }
                }
            ]
        }
    ]

});