/*
 * File: app/view/UpdateRecordFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define("ManagedUsers.view.UpdateRecordFormViewController", {
  extend: "Ext.app.ViewController",
  alias: "controller.updaterecordform",

  submitUpdate: function(button, e, eOpts) {
    var view = this.getView();
    // record = view.getRecord();
    // view.destroy();
    //record.commit();

    var store = Ext.getStore("Users");
    var record = Ext.create("ManagedUsers.model.User", {
      firstName: "Asad",
      lastName: "Rehman"
    });

    store.add(record);
    store.sync();
    Ext.getCmp("user_form_modal").close();
  },

  cancelUpdate: function(button, e, eOpts) {
    var view = this.getView(),
      record = view.getRecord();
    view.destroy();
    record.reject();

    Ext.getCmp("user_form_modal").close();
  },

  onLogin: function(button, e, eOpts) {
    var form = this.getView();

    if (form.validate()) {
      var view = this.getView();
      record = view.getRecord();
      

      var store = Ext.getStore("Users");
      

      if (form.config.createUser) {
        store.add(record);
        store.sync();
      } else {
        view.destroy();
        record.commit();
      
      }
      Ext.getCmp("user_form_modal").close();
    } else {
      Ext.Msg.alert("Manager Users", "Please fill the form correctly.");
    }
  },

  onCancel: function(button, e, eOpts) {
    var view = this.getView(),
      record = view.getRecord();

    if (view.config.createUser) {
      view.destroy();
    //  record.reject();
    } else {
      view.destroy();
      record.reject();
    }

    Ext.getCmp("user_form_modal").close();
  }
});
