/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QuickStart.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.maintabpanel',

    requires: [
        'QuickStart.view.MainTabPanelViewModel',
        'QuickStart.view.MainTabPanelViewController',
        'Ext.grid.Grid',
        'Ext.grid.column.Column',
        'Ext.Panel'
    ],

    controller: 'maintabpanel',
    viewModel: {
        type: 'maintabpanel'
    },

    items: [
        {
            xtype: 'grid',
            iconCls: 'x-fa fa-users',
            height: '100%',
            store: 'EmployeeStore',
            grouped: true,
            title: 'Employee Directory',
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    width: 100,
                    dataIndex: 'firstName',
                    text: 'First Name'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    width: 100,
                    dataIndex: 'lastName',
                    text: 'Last Name'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    width: 100,
                    dataIndex: 'phoneNumber',
                    text: 'Phone Number'
                }
            ],
            listeners: {
                childtap: 'onGridChildtap'
            }
        },
        {
            xtype: 'panel',
            html: '<h1>About Sencha</h1><br/>More than 10,000 customers and 60% of the Fortune 100 rely on Sencha solutions to deliver innovative applications that drive their businesses. With a longstanding commitment to web technologies, Sencha dramatically reduces the cost and complexity of developing and delivering enterprise applications across multiple device types.<br/><br/><h2>Create feature-rich HTML5 applications using JavaScript</h2><br/>Sencha Ext JS is the most comprehensive MVC/MVVM JavaScript framework for building feature-rich, cross-platform web applications targeting desktops, tablets, and smartphones. Ext JS leverages HTML5 features on modern browsers while maintaining compatibility and functionality for legacy browsers.<br/><br/>Ext JS features hundreds of high-performance UI widgets that are meticulously designed to fit the needs of the simplest as well as the most complex web applications. Ext JS templates and layout manager give you full control over your display irrespective of devices and screen sizes. An advanced charting package allows you to visualize large quantities of data. The framework includes a robust data package that can consume data from any backend data source. Ext JS also offers several out-of-the-box themes, and complete theming support that lets you build applications that reflect your brand. It also includes an accessibility package (ARIA) to help with Section 508 compliance.',
            padding: 20,
            iconCls: 'x-fa fa-info-circle',
            title: 'About Sencha'
        }
    ]

});