/*
 * File: app/view/DevcardsViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DevcardsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.devcards',

    config: {
        dataChangeCount: 0
    },

    onOpenFilterButtonTap: function(button, e, eOpts) {
        var filtersMenu = this.lookupReference('filters');
        filtersMenu.show();
    },

    onDevTap: function(list, location, eOpts) {
        let record = location.record;
        this.getViewModel().set('dev', record);
        let active = this.getView().animateActiveItem(1, 'slide');
        if (active.record !== record) {
            active.down('tabpanel').setActiveItem(0);
        }
        active.record = record;
    },

    onDevListButtonTap: function(button, e, eOpts) {
        this.getView().animateActiveItem(0, {type: 'slide', direction: 'right'});
    },

    /* In real app this event should be `load` but we are using inline data store with data config for esier preview  */
    onStoreDataChange: function(store, eOpts) {
        Ext.first('hero').getViewModel().set('devsCount', store.getCount());
    }

});