/*
 * File: app/view/FilterForm.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.FilterForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.filterform',

    requires: [
        'MyApp.view.FilterFormViewModel',
        'MyApp.view.FilterFormViewController',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.field.Checkbox'
    ],

    controller: 'filterform',
    viewModel: {
        type: 'filterform'
    },
    bodyPadding: 8,

    items: [
        {
            xtype: 'titlebar',
            docked: 'top',
            title: 'Filter By',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    iconCls: 'x-fa fa-close',
                    text: 'Close',
                    listeners: {
                        tap: 'onCloseButtonTap'
                    }
                }
            ]
        },
        {
            xtype: 'checkbox',
            label: 'ExtJS',
            labelWidth: 100,
            bind: {
                checked: '{extjs}'
            },
            listeners: {
                change: {
                    fn: 'onCheckboxChange4',
                    delay: 50
                }
            }
        },
        {
            xtype: 'checkbox',
            label: 'Touch',
            labelWidth: 100,
            bind: {
                checked: '{touch}'
            },
            listeners: {
                change: {
                    fn: 'onCheckboxChange3',
                    delay: 50
                }
            }
        },
        {
            xtype: 'checkbox',
            label: 'Architect',
            labelWidth: 100,
            bind: {
                checked: '{architect}'
            },
            listeners: {
                change: {
                    fn: 'onCheckboxChange2',
                    delay: 50
                }
            }
        },
        {
            xtype: 'checkbox',
            label: 'Themer',
            labelWidth: 100,
            bind: {
                checked: '{themer}'
            },
            listeners: {
                change: {
                    fn: 'onCheckboxChange1',
                    delay: 50
                }
            }
        },
        {
            xtype: 'checkbox',
            label: 'Inspector',
            labelWidth: 100,
            bind: {
                checked: '{inspector}'
            },
            listeners: {
                change: {
                    fn: 'onCheckboxChange',
                    delay: 50
                }
            }
        }
    ]

});