/*
 * File: app/view/Hero.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Hero', {
    extend: 'Ext.Container',
    alias: 'widget.hero',

    requires: [
        'MyApp.view.HeroViewModel',
        'Ext.Button'
    ],

    viewModel: {
        type: 'hero'
    },

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'component',
            flex: 1
        },
        {
            xtype: 'component',
            cls: 'hero-card-title',
            html: 'Sencha Devs'
        },
        {
            xtype: 'component',
            cls: 'hero-card-sub-title',
            html: 'Worldwide Sencha developers database.  Find <b><i>your</i></b> developer here.',
            padding: 10
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                this.up('main').setActiveItem(1);
            },
            margin: '60 0 0 0',
            iconCls: 'x-fa fa-arrow-circle-o-down',
            text: 'Get Started'
        },
        {
            xtype: 'component',
            flex: 1
        },
        {
            xtype: 'component',
            cls: 'dev-count',
            padding: 12,
            bind: {
                html: '<span class="dev-count-label">Devs:</span> <b>{devsCount}<b>'
            }
        }
    ]

});